local builtin = require("telescope.builtin")
vim.keymap.set("n", "<leader>pf", builtin.find_files, {})
vim.keymap.set("n", "<C-p>", function()
	require("telescope.builtin").buffers()
end)
vim.keymap.set("n", "<leader>pb", builtin.git_files, {})
vim.keymap.set("n", "<leader>ps", function()
	require("telescope.builtin").live_grep()
end)
vim.keymap.set("n", "<leader>vh", builtin.help_tags, {})
